from fastapi import APIRouter, Depends, HTTPException, Response
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from typing import List
from ..core.database import get_db
from ..core.redis import get_redis
from ..models.models import Page
import json
import redis.asyncio as redis
from ..schemas.page import Page as PageSchema

router = APIRouter(prefix="/api", tags=["public"])

@router.get("/pages/{slug}", response_model=PageSchema)
async def get_public_page(
    slug: str,
    db: AsyncSession = Depends(get_db),
    cache: redis.Redis = Depends(get_redis)
):
    # Try cache first
    cached_page = await cache.get(f"page:{slug}")
    if cached_page:
        return json.loads(cached_page)
        
    result = await db.execute(
        select(Page).where(Page.slug == slug, Page.status == "published")
    )
    db_page = result.scalars().first()
    if not db_page:
        raise HTTPException(status_code=404, detail="Page not found")
        
    # Serialize and cache
    # We need a way to serialize SQLAlchemy model to dict, or just use the schema
    page_data = PageSchema.from_orm(db_page).model_dump_json()
    await cache.setex(f"page:{slug}", 60, page_data) # 60s cache
    
    return db_page

@router.get("/pages", response_model=List[str])
async def list_public_slugs(
    db: AsyncSession = Depends(get_db)
):
    result = await db.execute(
        select(Page.slug).where(Page.status == "published")
    )
    return result.scalars().all()

@router.get("/robots.txt")
async def get_robots():
    content = "User-agent: *\nAllow: /\nSitemap: /sitemap.xml"
    return Response(content=content, media_type="text/plain")

@router.get("/sitemap.xml")
async def get_sitemap(
    db: AsyncSession = Depends(get_db)
):
    result = await db.execute(
        select(Page.slug).where(Page.status == "published")
    )
    slugs = result.scalars().all()
    
    # Very basic sitemap generation
    xml = '<?xml version="1.0" encoding="UTF-8"?>\n'
    xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    for slug in slugs:
        xml += f'  <url><loc>/{slug}</loc></url>\n'
    xml += '</urlset>'
    
    
    return Response(content=xml, media_type="application/xml")

@router.get("/llms.txt")
async def get_llms_txt(
    db: AsyncSession = Depends(get_db)
):
    result = await db.execute(
        select(Page).where(Page.status == "published")
    )
    pages = result.scalars().all()
    
    content = "# CANVAS CMS - Site Summary\n\n"
    content += "> Generated by CANVAS CMS\n\n"
    content += "## Pages\n\n"
    
    for p in pages:
        geo = p.schema.get("geo", {})
        if geo.get("enabled", True):
            content += f"### {p.title}\n"
            content += f"{geo.get('aiSummary', 'No summary available.')}\n\n"
            facts = geo.get("aiKeyFacts", [])
            for fact in facts:
                content += f"- {fact}\n"
            content += "\n"
            
    return Response(content=content, media_type="text/plain")

@router.get("/llms-full.txt")
async def get_llms_full_txt(
    db: AsyncSession = Depends(get_db)
):
    # Similar to llms.txt but with more detail if needed
    # For now, we'll make it same as llms.txt but could include full content clarity FAQ
    result = await db.execute(
        select(Page).where(Page.status == "published")
    )
    pages = result.scalars().all()
    
    content = "# CANVAS CMS - Full Site Context\n\n"
    
    for p in pages:
        geo = p.schema.get("geo", {})
        if geo.get("enabled", True):
            content += f"## {p.title} (/{p.slug})\n"
            content += f"Summary: {geo.get('aiSummary', '')}\n\n"
            content += "### Key Facts\n"
            for fact in geo.get("aiKeyFacts", []):
                content += f"- {fact}\n"
            
            faq = geo.get("contentClarity", {}).get("faqItems", [])
            if faq:
                content += "\n### FAQ\n"
                for item in faq:
                    content += f"Q: {item.get('question')}\nA: {item.get('answer')}\n\n"
            content += "---\n\n"
            
    return Response(content=content, media_type="text/plain")
